engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
  scss-lint:
    enabled: true
    exclude_paths:
      - "**.css"
ratings:
  paths:
    - "**.scss"
    - "**.css"
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
