engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
ratings:
  paths:
    - "**.css"
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
